### ISSUE TITLE
Typo: Uncapitalized "i" in PIVX

### ISSUE THREAD

**Issue by JSKitty** [FlorentG74/PIVX-Doc-Website-Content#35]
The "Knowledge Base" section of the front page displays PIVX with an uncapitalized I, (PiVX), highlighted below.
![image](https://user-images.githubusercontent.com/42538664/139094957-8d35b316-4b55-4064-867a-76fc1281dbe6.png)

**Comment by FlorentG74** [comment]
Fixed thanks for the report
