### ISSUE TITLE
Print icon no longer works.

### ISSUE THREAD

**Issue by PalmTreeVI** [FlorentG74/PIVX-Doc-Website-Content#36]
The print icon no longer triggers the browser print dialog, the print css does seem to still work blocking header, navigation, and footer from printing.

**Comment by FlorentG74** [comment]
It works locally but not on the production website - must be a security setup, i'll investigate further but will potentially need to take Kyeno's help

**Comment by FlorentG74** [comment]
![Capture d’écran 2021-11-12 à 22 26 32](https://user-images.githubusercontent.com/84814284/141536670-99c3f261-a0ca-4eb0-8eb1-6f0011dbf8bb.png)

Content Security Policy to be updated.

**Comment by FlorentG74** [comment]
Fixed by removing inline javascript
