### ISSUE TITLE
Certain pages have old git links

### ISSUE THREAD

**Issue by PalmTreeVI** [FlorentG74/PIVX-Doc-Website-Content#40]
It seems FAQ type pages have old git links.
Found these so far:
* https://docs.pivx.org/pivx-core-wallet/core-wallet-faq
* https://docs.pivx.org/mobile-hardware-wallets/mobile-hardware-faq
* https://docs.pivx.org/staking/staking-faq
* https://docs.pivx.org/masternodes-and-governance/masternodes-faq
* 
 
![Screenshot_2021-11-12_16-05-23](https://user-images.githubusercontent.com/64500998/141534755-f5304f77-ad62-4a34-9c92-b20413f5abd3.png)

**Comment by FlorentG74** [comment]
It was an issue on the FAQ template - I fixed it tonight (template in core website)
