### ISSUE TITLE
Error Page shows HTML tags

### ISSUE THREAD

**Issue by PalmTreeVI** [FlorentG74/PIVX-Doc-Website-Content#41]
Error page template displaying <p></p> tags, I think solution is to replace ```{{ page.content }}``` with ```{{ page.content|raw }}```
![Screenshot_2021-11-12_16-39-02](https://user-images.githubusercontent.com/64500998/141537726-a0d6c2c3-7188-4d42-a6b0-347aa0a6961d.png)
`

**Comment by FlorentG74** [comment]
Fixed w a commit in core website
